export type LineStyle =
  | 'dotted'
  | 'dashed'
  | 'solid'
  | 'double'
  | 'groove'
  | 'ridge'
  | 'inset'
  | 'outset'
export type Position = 'left' | 'top' | 'right' | 'bottom'
export type BtnType = 'primary' | 'success' | 'info' | 'warning' | 'danger'
